// Package contract generates the TypeScript a feature's routes declare.
//
// A feature exports its routes as a named group (route.Group). Generating
// reads those package-level values only: no application is built and no
// database is opened.
//
//	contract.Generate("frontend/generated", tickets.Routes, leads.Routes)
//
// writes one folder per group:
//
//	frontend/generated/tickets/entities.ts  the output types (and Types(...) extras)
//	frontend/generated/tickets/schemas.ts   the input types as Zod schemas, max: bounds kept
//	frontend/generated/tickets/routes.ts    the route table
//
// entities.ts and schemas.ts are left out of a group that has no such types.
// Every file starts with a line naming the go-core version that wrote it:
//
//	// This file is auto-generated by go-core v0.5.0. Do not edit manually.
//
// routes.ts is what the client builds typed requests from:
//
//	import { route } from "@wssto2/vue-core";
//	export const ticketsRoutes = {
//	  show: route<ShowInput, Ticket>("GET", "/tickets/:id", { permission: "tickets.ticket:view" }),
//	  events: route.raw("GET", "/events", { public: true }),
//	} as const;
//
// The key of a route is its Name without the group's prefix, camel-cased
// ("tickets.show" in group tickets is show, "identity.users.show" in group
// identity is usersShow). A route without a Name gets its method and path:
// GET /tickets/:id is getTicketsById, POST /tickets/:id/send-order is
// postTicketsByIdSendOrder. Two routes of a group with one key are an error.
//
// route.None as the input and route.Empty as the output become void. Inputs
// must be structs; outputs may also be primitives, slices and maps of those or
// of structs. A generic type (datatable.DatatableResult[Row]) is an error: go2ts
// names types by their Go name, so declare a named type for it.
package contract
