package contract

import (
	"errors"
	"fmt"
	"os"
	"path/filepath"
	"reflect"
	"regexp"
	"sort"
	"strings"

	"github.com/wssto2/go-core/go2ts"
	"github.com/wssto2/go-core/route"
)

var groupName = regexp.MustCompile(`^[a-z][a-z0-9]*(-[a-z0-9]+)*$`)

// Generate writes the TypeScript of every group into dir/<group>/. It reads
// the groups' declarations only. Problems are collected: the error lists every
// one, each with its fix.
func Generate(dir string, groups ...*route.Contract) error {
	var problems []string

	seen := map[string]bool{}

	for _, g := range groups {
		name := g.Name()

		switch {
		case !groupName.MatchString(name):
			problems = append(problems, fmt.Sprintf("group %q: the name is the folder and route table name, use lowercase words like \"tickets\" or \"price-rules\"", name))
			continue
		case seen[name]:
			problems = append(problems, fmt.Sprintf("group %q is given twice: pass each group once", name))
			continue
		}

		seen[name] = true

		if err := generateGroup(filepath.Join(dir, name), g); err != nil {
			problems = append(problems, fmt.Sprintf("group %q: %v", name, err))
		}
	}

	if len(problems) > 0 {
		return errors.New("contract: " + strings.Join(problems, "\n  "))
	}

	return nil
}

func generateGroup(dir string, g *route.Contract) error {
	plan, err := planOf(g)
	if err != nil {
		return err
	}

	if err := os.MkdirAll(dir, 0o755); err != nil { //nolint:gosec // generated sources are for the whole team to read
		return err
	}

	header := "// This file is auto-generated by go-core " + version() + ". Do not edit manually.\n"

	if len(plan.outs) > 0 {
		body, err := entitiesFile(plan.outs)
		if err != nil {
			return err
		}

		if err := os.WriteFile(filepath.Join(dir, "entities.ts"), []byte(header+body), 0o644); err != nil { //nolint:gosec // generated sources are for the whole team to read
			return err
		}
	}

	if len(plan.ins) > 0 {
		body, err := schemasFile(plan.ins)
		if err != nil {
			return err
		}

		if err := os.WriteFile(filepath.Join(dir, "schemas.ts"), []byte(header+body), 0o644); err != nil { //nolint:gosec // generated sources are for the whole team to read
			return err
		}
	}

	return os.WriteFile(filepath.Join(dir, "routes.ts"), []byte(header+routesFile(g.Name(), plan)), 0o644) //nolint:gosec // generated sources are for the whole team to read
}

// plan is what a group needs generated.
type plan struct {
	routes []routeLine
	ins    []any // input structs, for schemas.ts
	outs   []any // output and extra structs, for entities.ts
	inSet  map[string]bool
	outSet map[string]bool
	lists  bool // some output is a ListResult<Row>, imported next to route
}

type routeLine struct {
	key        string
	spec       route.Spec
	in, out    string // TypeScript type of the input and output; empty for raw routes
	usesIn     []string
	usesOut    []string
	permission string
}

func planOf(g *route.Contract) (*plan, error) {
	p := &plan{inSet: map[string]bool{}, outSet: map[string]bool{}}
	keys := map[string]string{}
	owner := map[string]reflect.Type{} // TypeScript name -> its Go type, to catch two types with one name

	claimAs := func(name string, t reflect.Type) error {
		if other, ok := owner[name]; ok && other != t {
			return fmt.Errorf("two types are named %s (%s and %s): rename one", name, other, t)
		}

		owner[name] = t

		return nil
	}
	claim := func(t reflect.Type) error { return claimAs(t.Name(), t) }

	for _, spec := range g.Specs() {
		line := routeLine{spec: spec, permission: spec.Permission}

		key := routeKey(g.Name(), spec)
		if other, dup := keys[key]; dup {
			return nil, fmt.Errorf("routes %s and %s both become %q: give one a .Name(...)", other, spec, key)
		}

		keys[key] = spec.String()
		line.key = key

		if spec.Untyped {
			p.routes = append(p.routes, line)
			continue
		}

		if problems := spec.PathProblems(); len(problems) > 0 {
			return nil, errors.New(strings.Join(problems, "\n  "))
		}

		if spec.In == reflect.TypeFor[route.None]() {
			line.in = "void"
		} else {
			if spec.In.Kind() != reflect.Struct {
				return nil, fmt.Errorf("route %s: the input %s is not a struct (use route.None for no input)", spec, spec.In)
			}

			if err := checkNamed(spec, spec.In); err != nil {
				return nil, err
			}

			if err := claim(spec.In); err != nil {
				return nil, err
			}

			line.in = spec.In.Name()
			line.usesIn = []string{spec.In.Name()}

			if !p.inSet[spec.In.Name()] {
				p.inSet[spec.In.Name()] = true
				p.ins = append(p.ins, reflect.New(spec.In).Elem().Interface())
			}
		}

		if spec.Out == reflect.TypeFor[route.Empty]() {
			line.out = "void"
		} else {
			expr, structs, err := tsType(spec, spec.Out, &p.lists)
			if err != nil {
				return nil, err
			}

			line.out = expr

			for _, st := range structs {
				if err := claim(st); err != nil {
					return nil, err
				}

				line.usesOut = append(line.usesOut, st.Name())

				if !p.outSet[st.Name()] {
					p.outSet[st.Name()] = true
					p.outs = append(p.outs, reflect.New(st).Elem().Interface())
				}
			}
		}

		p.routes = append(p.routes, line)
	}

	for _, t := range g.ExtraTypes() {
		if t.Kind() != reflect.Struct {
			return nil, fmt.Errorf("Types(%s): only structs can be generated, a %s has no values to list", t, t.Kind())
		}

		if err := checkNamed(route.Spec{}, t); err != nil {
			return nil, err
		}

		if err := claim(t); err != nil {
			return nil, err
		}

		if !p.outSet[t.Name()] {
			p.outSet[t.Name()] = true
			p.outs = append(p.outs, reflect.New(t).Elem().Interface())
		}
	}

	if err := planEnums(p, g, claimAs); err != nil {
		return nil, err
	}

	for _, r := range p.routes {
		for _, n := range r.usesIn {
			if p.outSet[n] {
				return nil, fmt.Errorf("%s is both the input of a route and an output: give them different names (entities.ts and schemas.ts would both export it)", n)
			}
		}
	}

	return p, nil
}

// isListResult reports whether t is datatable.DatatableResult[Row]: the one
// generic go-core type with a TypeScript form (ListResult<Row>, which vue-core
// exports with exactly the datatable wire shape).
func isListResult(t reflect.Type) bool {
	return t.PkgPath() == "github.com/wssto2/go-core/datatable" && strings.HasPrefix(t.Name(), "DatatableResult[")
}

// checkNamed refuses what go2ts cannot name: a generic or anonymous struct.
func checkNamed(spec route.Spec, t reflect.Type) error {
	if t.Name() == "" || strings.ContainsAny(t.Name(), "[]") {
		where := "Types"
		if spec.Path != "" {
			where = "route " + spec.String()
		}

		return fmt.Errorf("%s: %s cannot be generated, go2ts names types by their Go name: declare a named, non-generic type", where, t)
	}

	return nil
}

// tsType renders t as a TypeScript type and lists the named structs it needs.
func tsType(spec route.Spec, t reflect.Type, lists *bool) (string, []reflect.Type, error) {
	switch t.Kind() {
	case reflect.Pointer:
		expr, st, err := tsType(spec, t.Elem(), lists)
		return expr + " | null", st, err
	case reflect.Bool:
		return "boolean", nil, nil
	case reflect.String:
		return "string", nil, nil
	case reflect.Int, reflect.Int8, reflect.Int16, reflect.Int32, reflect.Int64,
		reflect.Uint, reflect.Uint8, reflect.Uint16, reflect.Uint32, reflect.Uint64,
		reflect.Float32, reflect.Float64:
		return "number", nil, nil
	case reflect.Slice, reflect.Array:
		expr, st, err := tsType(spec, t.Elem(), lists)
		if strings.Contains(expr, " | ") {
			expr = "(" + expr + ")"
		}

		return expr + "[]", st, err
	case reflect.Map:
		if t.Key().Kind() != reflect.String {
			break
		}

		expr, st, err := tsType(spec, t.Elem(), lists)

		return "Record<string, " + expr + ">", st, err
	case reflect.Struct:
		if t.PkgPath() == "time" && t.Name() == "Time" {
			return "string", nil, nil
		}

		if isListResult(t) {
			row, _ := t.FieldByName("Data")
			expr, st, err := tsType(spec, row.Type.Elem(), lists)
			*lists = true

			return "ListResult<" + expr + ">", st, err
		}

		if err := checkNamed(spec, t); err != nil {
			return "", nil, err
		}

		return t.Name(), []reflect.Type{t}, nil
	}

	return "", nil, fmt.Errorf("route %s: the type %s has no TypeScript form here: wrap it in a named struct", spec, t)
}

// entitiesFile renders GenerateTypes' one-file-per-type output as one file.
func entitiesFile(structs []any) (string, error) {
	files, err := generated(func(dir string) error { return go2ts.GenerateTypes(structs, dir) })
	if err != nil {
		return "", err
	}

	var b strings.Builder

	for _, name := range sortedKeys(files) {
		b.WriteString(body(files[name]) + "\n")
	}

	return strings.TrimRight(b.String(), "\n") + "\n", nil
}

// schemasFile renders GenerateSchemas' output as one file, each schema after
// the ones it uses (a const cannot be read before its line).
func schemasFile(structs []any) (string, error) {
	files, err := generated(func(dir string) error { return go2ts.GenerateSchemas(structs, dir) })
	if err != nil {
		return "", err
	}

	var (
		b     strings.Builder
		done  = map[string]bool{}
		visit func(name string)
		uses  = regexp.MustCompile(`(?m)^import \{ (\w+)Schema \} from '\./\w+';$`)
	)

	b.WriteString("import { z } from 'zod';\n\n")

	visit = func(name string) {
		if done[name] {
			return
		}

		done[name] = true

		for _, m := range uses.FindAllStringSubmatch(files[name], -1) {
			if _, ok := files[m[1]]; ok {
				visit(m[1])
			}
		}

		b.WriteString(body(files[name]) + "\n")
	}

	for _, name := range sortedKeys(files) {
		visit(name)
	}

	return strings.TrimRight(b.String(), "\n") + "\n", nil
}

// generated runs a go2ts generator into a scratch directory and returns the
// files it wrote by type name.
func generated(run func(dir string) error) (map[string]string, error) {
	dir, err := os.MkdirTemp("", "gocore-contract-*")
	if err != nil {
		return nil, err
	}

	defer func() { _ = os.RemoveAll(dir) }()

	if err := run(dir); err != nil {
		return nil, err
	}

	entries, err := os.ReadDir(dir)
	if err != nil {
		return nil, err
	}

	files := map[string]string{}

	for _, e := range entries {
		src, err := os.ReadFile(filepath.Join(dir, e.Name())) //nolint:gosec // our own scratch directory
		if err != nil {
			return nil, err
		}

		files[strings.TrimSuffix(e.Name(), ".ts")] = string(src)
	}

	return files, nil
}

// body is a go2ts file without its header and its imports.
func body(src string) string {
	var keep []string

	for _, line := range strings.Split(src, "\n") {
		if strings.HasPrefix(line, "// This file is auto-generated") || strings.HasPrefix(line, "import ") {
			continue
		}

		keep = append(keep, line)
	}

	return strings.TrimSpace(strings.Join(keep, "\n")) + "\n"
}

func sortedKeys(m map[string]string) []string {
	keys := make([]string, 0, len(m))
	for k := range m {
		keys = append(keys, k)
	}

	sort.Strings(keys)

	return keys
}

// planEnums adds the group's enumerations: written to entities.ts, and to
// schemas.ts when an input uses them.
func planEnums(p *plan, g *route.Contract, claimAs func(string, reflect.Type) error) error {
	seen := map[reflect.Type]bool{}

	var ins, outs []any

	for _, e := range g.Enums() {
		t := e.Type()

		switch {
		case t.Kind() != reflect.String || t.Name() == "" || t.PkgPath() == "":
			return fmt.Errorf("enum of %s: an enumeration needs a named string type (type Status string), not %s", t, t)
		case len(e.Values()) == 0:
			return fmt.Errorf("enum of %s has no values: pass the constants, route.Enum(%sA, %sB)", t, t.Name(), t.Name())
		case seen[t]:
			return fmt.Errorf("enum of %s is declared twice in group %q: list it once in Types", t, g.Name())
		}

		seen[t] = true

		name := e.Name()

		if err := claimAs(name, t); err != nil {
			return err
		}

		values := e.Values()
		if dup := firstDuplicate(values); dup != "" {
			return fmt.Errorf("enum of %s lists %q twice", t, dup)
		}

		out, in := any(go2ts.Enum(t, values)), any(go2ts.EnumIfUsed(t, values))
		if name != t.Name() {
			out, in = go2ts.As(out, name), go2ts.As(in, name)
		}

		outs, ins = append(outs, out), append(ins, in)
	}

	p.outs = append(p.outs, outs...)

	if len(p.ins) > 0 {
		p.ins = append(p.ins, ins...)
	}

	return nil
}

func firstDuplicate(values []string) string {
	seen := map[string]bool{}

	for _, v := range values {
		if seen[v] {
			return v
		}

		seen[v] = true
	}

	return ""
}
