package main

import (
	"os"
	"path/filepath"
	"strings"
	"testing"
)

func TestGenerateWritesAFolderPerModule(t *testing.T) {
	dir := t.TempDir()
	if err := generate(dir); err != nil {
		t.Fatal(err)
	}

	for _, module := range []string{"identity", "access", "notification", "events"} {
		src, err := os.ReadFile(filepath.Join(dir, module, "routes.ts")) //nolint:gosec // a temp dir of this test
		if err != nil {
			t.Fatal(err)
		}

		if !strings.HasPrefix(string(src), "// This file is auto-generated by go-core ") {
			t.Errorf("%s/routes.ts has no version header:\n%.120s", module, src)
		}

		if !strings.Contains(string(src), `from "@wssto2/vue-core/client"`) {
			t.Errorf("%s/routes.ts does not import from vue-core/client", module)
		}
	}
}
