// This file is auto-generated by go-core v0.0.0-test. Do not edit manually.
export type Person = {
  id: number;
  name: string;
};

export type Row = {
  id: number;
  title: string;
};

export type Stats = {
  open: number;
};

export type Ticket = {
  id: number;
  title: string;
  assignee: Person | null;
  tags: string[];
  opened: string;
};
