package go2ts_test

import (
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"github.com/wssto2/go-core/go2ts"
	"github.com/wssto2/go-core/go2ts/testtypesa"
	"github.com/wssto2/go-core/go2ts/testtypesb"
)

// --- test types ---

type SimpleUser struct {
	ID   int    `json:"id"`
	Name string `json:"name"`
	Age  int    `json:"age,omitempty"`
}

type WithPointer struct {
	ID    int      `json:"id"`
	Score *float64 `json:"score"`
}

type Nested struct {
	ID      int        `json:"id"`
	Address AddressDTO `json:"address"`
}

type AddressDTO struct {
	Street string `json:"street"`
	City   string `json:"city"`
}

type WithSlice struct {
	Tags []string `json:"tags"`
}

type Lead struct {
	ID int `json:"id"`
}

type WithPointerSlice struct {
	Leads []*Lead `json:"leads,omitempty"`
}

type WithBool struct {
	Active bool `json:"active"`
}

type WithSkipped struct {
	ID     int    `json:"id"`
	Secret string `json:"-"`
}

type OfferWithPricing struct {
	Pricing testtypesa.Pricing `json:"pricing"`
}

type InvoiceWithPricing struct {
	Pricing testtypesb.Pricing `json:"pricing"`
}

// --- tests ---

func TestGenerateTypes_SimpleStruct(t *testing.T) {
	dir := t.TempDir()
	require.NoError(t, go2ts.GenerateTypes([]interface{}{SimpleUser{}}, dir))

	content, err := os.ReadFile(filepath.Join(dir, "SimpleUser.ts"))
	require.NoError(t, err)
	src := string(content)

	assert.Contains(t, src, "export type SimpleUser")
	assert.Contains(t, src, "id: number")
	assert.Contains(t, src, "name: string")
	// omitempty → optional field
	assert.Contains(t, src, "age?: number")
}

func TestGenerateTypes_PointerFieldIsNullable(t *testing.T) {
	dir := t.TempDir()
	require.NoError(t, go2ts.GenerateTypes([]interface{}{WithPointer{}}, dir))

	content, err := os.ReadFile(filepath.Join(dir, "WithPointer.ts"))
	require.NoError(t, err)
	src := string(content)

	assert.Contains(t, src, "score: number | null")
}

func TestGenerateTypes_NestedStructCreatesChildFile(t *testing.T) {
	dir := t.TempDir()
	require.NoError(t, go2ts.GenerateTypes([]interface{}{Nested{}}, dir))

	// Parent file should exist
	parent, err := os.ReadFile(filepath.Join(dir, "Nested.ts"))
	require.NoError(t, err)
	assert.Contains(t, string(parent), "address: AddressDTO")
	assert.Contains(t, string(parent), "import type { AddressDTO }")

	// Child file should be generated
	child, err := os.ReadFile(filepath.Join(dir, "AddressDTO.ts"))
	require.NoError(t, err)
	assert.Contains(t, string(child), "street: string")
	assert.Contains(t, string(child), "city: string")
}

func TestGenerateTypes_SliceField(t *testing.T) {
	dir := t.TempDir()
	require.NoError(t, go2ts.GenerateTypes([]interface{}{WithSlice{}}, dir))

	content, err := os.ReadFile(filepath.Join(dir, "WithSlice.ts"))
	require.NoError(t, err)
	assert.Contains(t, string(content), "tags: string[]")
}

func TestGenerateTypes_PointerSliceField(t *testing.T) {
	dir := t.TempDir()
	require.NoError(t, go2ts.GenerateTypes([]interface{}{WithPointerSlice{}}, dir))

	content, err := os.ReadFile(filepath.Join(dir, "WithPointerSlice.ts"))
	require.NoError(t, err)
	assert.Contains(t, string(content), "leads?: Lead[]")
	assert.NotContains(t, string(content), "Lead | null[]")
}

func TestGenerateTypes_BoolField(t *testing.T) {
	dir := t.TempDir()
	require.NoError(t, go2ts.GenerateTypes([]interface{}{WithBool{}}, dir))

	content, err := os.ReadFile(filepath.Join(dir, "WithBool.ts"))
	require.NoError(t, err)
	assert.Contains(t, string(content), "active: boolean")
}

func TestGenerateTypes_SkipsJsonDashFields(t *testing.T) {
	dir := t.TempDir()
	require.NoError(t, go2ts.GenerateTypes([]interface{}{WithSkipped{}}, dir))

	content, err := os.ReadFile(filepath.Join(dir, "WithSkipped.ts"))
	require.NoError(t, err)
	src := string(content)

	assert.Contains(t, src, "id: number")
	assert.NotContains(t, src, "Secret")
	assert.NotContains(t, src, "secret")
}

func TestGenerateTypes_OutputHasAutoGeneratedComment(t *testing.T) {
	dir := t.TempDir()
	require.NoError(t, go2ts.GenerateTypes([]interface{}{SimpleUser{}}, dir))

	content, err := os.ReadFile(filepath.Join(dir, "SimpleUser.ts"))
	require.NoError(t, err)
	assert.True(t, strings.HasPrefix(string(content), "// This file is auto-generated."))
}

func TestGenerateTypes_DeduplicatesNestedTypes(t *testing.T) {
	dir := t.TempDir()
	// Provide AddressDTO twice indirectly — should only generate one file
	require.NoError(t, go2ts.GenerateTypes([]interface{}{Nested{}, AddressDTO{}}, dir))

	// AddressDTO.ts should exist
	_, err := os.ReadFile(filepath.Join(dir, "AddressDTO.ts"))
	require.NoError(t, err)
}

func TestGenerateTypes_RenamesCollidingNestedTypes(t *testing.T) {
	dir := t.TempDir()

	require.NoError(t, go2ts.GenerateTypes([]interface{}{OfferWithPricing{}, InvoiceWithPricing{}}, dir))

	offerFile, err := os.ReadFile(filepath.Join(dir, "OfferWithPricing.ts"))
	require.NoError(t, err)
	invoiceFile, err := os.ReadFile(filepath.Join(dir, "InvoiceWithPricing.ts"))
	require.NoError(t, err)

	assert.Contains(t, string(offerFile), "pricing: Pricing")
	assert.Contains(t, string(offerFile), "import type { Pricing }")
	assert.Contains(t, string(invoiceFile), "pricing: InvoiceWithPricingPricing")
	assert.Contains(t, string(invoiceFile), "import type { InvoiceWithPricingPricing }")

	pricingFile, err := os.ReadFile(filepath.Join(dir, "Pricing.ts"))
	require.NoError(t, err)
	assert.Contains(t, string(pricingFile), "net: number")

	renamedFile, err := os.ReadFile(filepath.Join(dir, "InvoiceWithPricingPricing.ts"))
	require.NoError(t, err)
	assert.Contains(t, string(renamedFile), "gross: number")
}

func TestGenerateTypes_ErrorOnNonStruct(t *testing.T) {
	dir := t.TempDir()
	err := go2ts.GenerateTypes([]interface{}{"not a struct"}, dir)
	assert.Error(t, err)
}

func TestGenerateTypes_CreatesOutputDirectory(t *testing.T) {
	base := t.TempDir()
	dir := filepath.Join(base, "deep", "nested", "dir")
	require.NoError(t, go2ts.GenerateTypes([]interface{}{SimpleUser{}}, dir))

	_, err := os.Stat(dir)
	assert.NoError(t, err)
}
